### ISSUE TITLE
Inconsistent type for `Domain.zone_history`

### ISSUE THREAD

**Issue by ghost** [happyDomain/python-sdk#1]
`Domain.zone_history` is modified in two places ([1](https://github.com/happyDomain/python-sdk/blob/7325b3956bda25f1d67730ea2780250791c8fd1d/happydomain/domain.py#LL57C1-L67C18) and [2](https://github.com/happyDomain/python-sdk/blob/7325b3956bda25f1d67730ea2780250791c8fd1d/happydomain/domain.py#L9-L17)):

```py
class Domain:

    def import_zone(self):
        r = self._session.session.post(
            self._session.baseurl + "/api/domains/" + quote(self.id) + "/import_zone",
        )

        ...

        zm = ZoneMeta(self._session, **r.json())
        self.zone_history.append(zm) # <--- HERE
        return zm
```

In the snippet above, we can see the `Domain.zone_history` has a **`ZoneMeta` object appended**.

```py
class Domain:

    def __init__(self, _session, id, id_owner, id_provider, domain, zone_history, group=""):
        self._session = _session

        self.id = id
        self.id_owner = id_owner
        self.id_provider = id_provider
        self.domain = domain
        self.group = group
        self.zone_history = zone_history if zone_history is not None else [] # <--- HERE
```

`Domain.__init__()` is used twice:

- In [`HappyDomain.domain_list()`](https://github.com/happyDomain/python-sdk/blob/7325b3956bda25f1d67730ea2780250791c8fd1d/happydomain/api.py#L41).
- In [`Provider.domain_add()`](https://github.com/happyDomain/python-sdk/blob/7325b3956bda25f1d67730ea2780250791c8fd1d/happydomain/provider.py#L27).

The API endpoint `GET /api/domains` used by `domain_list()` returns a list of zone ID strings; `Domain.zone_history` is then set to this **list of `str`**. I **_assume_** that the behavior is similar for `POST /api/domains` used by `domain_add()`.

Therefore, the types for `Domain.zone_history` are inconsistent. The list contains objects of type `ZoneMeta` or `str`.

A simple fix is to change how `Domain.import_zone()` modifies the `zone_history`:

```diff
class Domain:

    def import_zone(self):
        r = self._session.session.post(
            self._session.baseurl + "/api/domains/" + quote(self.id) + "/import_zone",
        )

        if r.status_code > 300:
            raise HappyError(r.status_code, **r.json())

        zm = ZoneMeta(self._session, **r.json())
-       self.zone_history.append(zm)
+       self.zone_history.append(zm.id)
        return zm
```

Along with this, it would be nice to change the name from `zone_history` to `id_zone_history`.

This issue impacts the [Ansible Collection](https://github.com/happyDomain/ansible-collection/). The code expects the `zone_history` to be of type `Zone` or `ZoneMeta`, and therefore to have an `id` property. Once a fix is released to fix this issue, the collection should be updated.

**Comment by nemunaire** [comment]
Hi @JqrfYvZm!

Thanks for your report!

In fact the inconsistency is located in the service's API: in order to reduce the amount of useless requests made to the database, a call to `domain_list` does only returns a list of zone IDs, instead of a list of metadata.

However, the expected type here is really a list of metadata, for all others calls.

To fix the inconsistency, we introduced a new intermediate type `UncompleteZoneMeta` that behave exactly likes a `ZoneMeta`, but either returns directly the zone ID if asked, or retrieves the full zone's metadata.

This permits to resolve the [linked issue](https://github.com/happyDomain/ansible-collection/issues/1) with zero action.
